Whiteboard/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Whiteboard.Data;
using Whiteboard.Models.DataModels.Modules;
using Whiteboard.Models.DataModels.Accounts;
using Whiteboard.Models.DataModels.Messaging;
using Whiteboard.Models.ViewModels.Messaging;
using Whiteboard.Repositories;
using Whiteboard.Models.ViewModels.Modules;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Primitives;
using System.IO;
using System.Net.Mime;

namespace Whiteboard.Controllers {
    [Authorize]
    public class ModuleController : Controller {

        private readonly AppIdentityDbContext _dbContext;
        private readonly ModuleRepository _moduleRepository;
        private readonly AppUserRepository _appUserRepository;
        private readonly MessageRepository _messageRepository;
        private readonly HtmlEncoder _htmlEncoder;
        private readonly JavaScriptEncoder _jsEncoder;

        public ModuleController(AppIdentityDbContext appIdentityDbContext,
                UserManager<AppUser> userManager,
                SignInManager<AppUser> signInManager,
                HtmlEncoder htmlEncoder, JavaScriptEncoder jsEncoder) {

            _dbContext = appIdentityDbContext;

            _moduleRepository = new ModuleRepository(appIdentityDbContext);

            _appUserRepository = new AppUserRepository(appIdentityDbContext,
                userManager, signInManager);

            _messageRepository = new MessageRepository(appIdentityDbContext);

            _htmlEncoder = htmlEncoder;
            _jsEncoder = jsEncoder;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string code) {
            AccessResult accessResult = await AccessModule(code);

            if(accessResult.Redirect != null) {
                return accessResult.Redirect;
            }

            AppUser user = accessResult.User;
            Module module = accessResult.Module;

            ModuleHomeViewModel moduleHomeViewModel = new ModuleHomeViewModel(
                _jsEncoder, _htmlEncoder, module, user.AccessDisplays);

            return user.GetModuleIndexPage(this, moduleHomeViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Material(string code) {
            AccessResult accessResult = await AccessModule(code);

            if (accessResult.Redirect != null) {
                return accessResult.Redirect;
            }

            Module module = accessResult.Module;
            AppUser user = accessResult.User;

            ModuleMaterialViewModel moduleMaterialViewModel =
                new ModuleMaterialViewModel(_jsEncoder, _htmlEncoder, module,
                user.AccessDisplays);

            return await user.GetMaterialPage(this, _appUserRepository,
                moduleMaterialViewModel);
        }

        [Authorize(Roles = Roles.DEVELOPER)]
        [HttpGet]
        public async Task<IActionResult> MessagesDisplayTest() {
            AppUser john = await _appUserRepository.GetFromNameAsync(
                AppUserDBInitializer.LECTURER_MEMBER1_USERNAME);

            AppUser jim = await _appUserRepository.GetFromNameAsync(
                AppUserDBInitializer.STUDENT_CUSTOMER1_USERNAME);

            List<Message> messages = new List<Message>();

            TextMessage firstTextMessage = new TextMessage {
                Text = "Hello",
                Sender = john
            };

            TextMessage secondTextMessage = new TextMessage {
                Text = "Hi",
                Sender = jim
            };

            TextMessage thirdTextMessage = new TextMessage {
                Text = "How are you doing?",
                Sender = john
            };

            TextMessage fourthTextMessage = new TextMessage {
                Text = "Fine",
                Sender = jim
            };

            messages.Add(firstTextMessage);
            messages.Add(secondTextMessage);
            messages.Add(thirdTextMessage);
            messages.Add(fourthTextMessage);

            MessageBoard messageBoard = new MessageBoard {
                Messages = messages
            };

            MessageBoardViewModel messageBoardViewModel =
                new MessageBoardViewModel(_jsEncoder, _htmlEncoder,
                messageBoard);

            return View(messageBoardViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReceiveMessage(
                int msgBoardID, string text) {

            MessageBoard messageBoard = await _messageRepository
                .GetMessageBoardAsync(msgBoardID);

            AppUser user = await _appUserRepository.GetAsync(User);

            if(messageBoard == null || text == null) {
                return BadRequest();
            }

            bool isMember = await _messageRepository.IsMemberAsync(
                user, messageBoard);

            if(!isMember) {
                return Unauthorized();
            }

            TextMessage textMessage = new TextMessage(
                user, DateTime.Now, text);

            await _messageRepository.AddMessageAsync(user, textMessage,
                messageBoard);

            string messageHtml = textMessage.GetDisplay(
                _jsEncoder,_htmlEncoder);

            return Content(messageHtml);
        }

        [Authorize(Policy = Claims.CAN_WRITE_MATERIAL)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMaterial(string moduleCode,
                string name) {

            AccessResult accessResult = await AccessModule(moduleCode);

            if (accessResult.Redirect != null) {
                return Unauthorized();
            }

            Module module = accessResult.Module;
            Lecture lecture = new Lecture(name);

            await _moduleRepository.AddMaterialAsync(module, lecture);

            AddedMaterialViewModel addedMaterialViewModel =
                new AddedMaterialViewModel(lecture);

            return Json(addedMaterialViewModel);
        }

        [Authorize(Policy = Claims.CAN_WRITE_MATERIAL)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMaterialItem() {
            IFormFile formFile = Request.Form.Files[0];

            StringValues moduleCodeValues;
            Request.Form.TryGetValue("moduleCode", out moduleCodeValues);

            StringValues materialIdValues;
            Request.Form.TryGetValue("materialId", out materialIdValues);

            StringValues nameValues;
            Request.Form.TryGetValue("name", out nameValues);

            string moduleCode = moduleCodeValues.ToString();
            long materialId = Convert.ToInt64(materialIdValues.ToString());
            string name = nameValues.ToString();

            AccessResult accessResult = await AccessModule(moduleCode);

            if (accessResult.Redirect != null) {
                return Unauthorized();
            }

            Lecture lecture = await _moduleRepository.GetMaterialAsync(
                moduleCode, materialId);

            if(lecture == null) {
                return NotFound();
            }

            byte[] file;

            using (MemoryStream stream = new MemoryStream()) {
                await formFile.CopyToAsync(stream);
                file = stream.ToArray();
            }

            Module module = accessResult.Module;

            Resource resource = new Resource(name, file, formFile.ContentType,
                formFile.FileName);

            await _moduleRepository.AddResourceAsync(module, lecture,
                resource);

            return Content(resource.Id.ToString());
        }

        [HttpGet]
        public async Task<IActionResult> DownloadResource(string moduleCode,
                long materialId, long itemId) {

            AccessResult accessResult = await AccessModule(moduleCode);

            if (accessResult.Redirect != null) {
                return Unauthorized();
            }

            AppUser user = accessResult.User;
            Module module = accessResult.Module;

            Lecture lecture = await _moduleRepository.GetMaterialAsync(
                moduleCode, materialId);

            if(lecture == null) {
                return BadRequest();
            }

            Resource resource = await _moduleRepository.GetResourceAsync(
                moduleCode, materialId, itemId);

            if (resource == null) {
                return BadRequest();
            }

            await user.SeenResource(_moduleRepository, module,
                lecture, resource);

            var cd = new ContentDisposition() {
                FileName = resource.FileName,
                Inline = true
            };

            Response.Headers.Append("Content-Disposition", cd.ToString());

            return File(resource.File, resource.FileContentType);
        }

        [Authorize(Policy = Claims.CAN_READ_ANALYTICS)]
        [HttpGet]
        public async Task<IActionResult> Analytics(string code) {
            AccessResult accessResult = await AccessModule(code);

            if (accessResult.Redirect != null) {
                return accessResult.Redirect;
            }

            AppUser user = accessResult.User;
            Module module = accessResult.Module;

            ModuleAnalyticsViewModel moduleAnalyticsViewModel =
                new ModuleAnalyticsViewModel(module, user.AccessDisplays);

            await moduleAnalyticsViewModel.InitialiseAsync(_dbContext, module);

            return View("Lecturer/Analytics", moduleAnalyticsViewModel);
        }

        private async Task<AccessResult> AccessModule(string code) {
            if (code == null) {

Whiteboard/Views/Shared/_EmptyNavBarPartial.cshtml
@model Whiteboard.Models.ViewModels.IAccessDisplayable

Whiteboard/Views/Shared/_Layout.cshtml
@model Whiteboard.Models.ViewModels.IAccessDisplayable

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Whiteboard</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <link rel="stylesheet" href="~/css/wbstyle.css" />
    <script src="~/scripts/jquery-3.3.1.min.js"></script>
    <script src="~/scripts/MessageContents.js"></script>
</head>
<body>
    <form id="__AntiForgeryForm" action="#" method="post">@Html.AntiForgeryToken()</form>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Whiteboard</a>
            </div>
            @{await Html.RenderPartialAsync("_LoginPartial", Model);}
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Whiteboard</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Whiteboard/Views/Shared/_ManageAccountsTablePartial.cshtml
@using Whiteboard.Models.ViewModels.Accounts
@model UsersSelectViewModel

<table class="manage-accounts-table">
    <tr>
        <th class="common-label">Username</th>
        @foreach (string claimName in Model.AvailableClaims) {
            <th class="common-label">@claimName</th>
        }
        <th class="manage-accounts-cell common-label">Delete?</th>
    </tr>
    @foreach (UserSelectViewModel user in Model.Users) {
        <tr data-username="@user.Username">
            <td>
                <a asp-controller="Account" asp-action="ManageAccount" asp-route-username="@user.Username">@user.Username</a>
            </td>
            @foreach (string claim in user.Claims) {
                <td>@claim</td>
            }
            <td>
                <button class="common-btn delete-button">Delete</button>
            </td>
        </tr>
    }
</table>

Whiteboard/Views/Shared/_MaterialDisplayPartial.cshtml
@model Whiteboard.Models.ViewModels.Modules.LectureViewModel

"<div class='material-display table-material'>" +
"   <div class='row-field'>" +
"       <div class='material-header cell-field'>" +
"           <p class='material-title'>" + textName + "</p>" +
"       </div>" +
"       <div class='material-footer cell-field'>" +
"           <div class='files-display'>" +
"               <div class='table-files'>" +
"                   <div class='row-field file-icons'>" +
"                       <div class='add-item-icon cell-field'></div>" +
"                   </div>" +
"                   <div class='row-field file-names'>" +
"                       <div class='add-item-name cell-field'></div>" +
"                   </div>" +
"               </div>" +
"           </div>" +
"       </div>" +
"   </div>" +
"</div>"

Whiteboard/Views/Shared/_MaterialScriptsPartial.cshtml
<script src="~/scripts/MaterialManager.js"></script>

<script>
    function createItemIcon(materialId, itemId) {
        return createItemFileIcon("@Model.Code", materialId, itemId,
            "@Url.Content("~/images/File-Icon.svg")")
    }

$(document).ready(function () {
    $("#material").on("click", ".show-comments", function () {
        var showComments = $(this);
        var messageBoardId = showComments.attr("data-message-board-id");

        var messenger = $("#messenger-" + messageBoardId);

        messenger.removeClass("hide-message-board")
            .addClass("show-message-board");

        showComments.removeClass("show-comments")
            .addClass("hide-comments");

        showComments.html("Hide comments");
    });

    $("#material").on("click", ".hide-comments", function () {
        var showComments = $(this);
        var messageBoardId = showComments.attr("data-message-board-id");

        var messenger = $("#messenger-" + messageBoardId);

        messenger.removeClass("show-message-board")
            .addClass("hide-message-board");

        showComments.removeClass("hide-comments")
            .addClass("show-comments");

        showComments.html("Show comments");
    });
});
</script>

Whiteboard/Views/Shared/_MessengerPartial.cshtml
@using Whiteboard.Models.ViewModels.Messaging
@model Whiteboard.Models.ViewModels.Messaging.MessageBoardViewModel

<script>
    var messages = "";

    @foreach (MessageViewModel message in Model.Messages) {
        <text>
            messages += "@Html.Raw(message.Contents)";
        </text>
    }

    createMessenger(@Model.Id, messages);
</script>

Whiteboard/Views/Shared/_MessengerScriptsPartial.cshtml
<script src="~/scripts/SecurityLib.js"></script>
<script src="~/scripts/MessagingHandlers.js"></script>

<script>
    $(document).ready(function () {
        setupHandlers('@Url.Action("ReceiveMessage", "Module")')
    });
</script>

Whiteboard/Views/Shared/_ModuleIndexPartial.cshtml
@model Whiteboard.Models.ViewModels.Modules.ModuleHomeViewModel

@{await Html.RenderPartialAsync("_MessengerScriptsPartial");}

<h2 class="common-heading">@Model.Code: @Model.Name</h2>

@{await Html.RenderPartialAsync("_MessengerPartial",
          Model.ModuleMessageBoard);}

Whiteboard/Views/Shared/_ModuleNavBarPartial.cshtml
@model Whiteboard.Models.ViewModels.IAccessDisplayable

<li><a asp-controller="Module" asp-action="Index" asp-route-code="@ViewData["ModuleCode"]">Module Home</a></li>
<li><a asp-controller="Module" asp-action="Material" asp-route-code="@ViewData["ModuleCode"]">Material</a></li>

@foreach(AccessDisplay accessDisplay in Model.GetAccessDisplays()) {
    @if(accessDisplay.Access.Equals(AccessDisplay.MODULE_ACCESS)) {
        <li><a asp-controller="@accessDisplay.Controller" asp-action="@accessDisplay.Action" asp-route-code="@ViewData["ModuleCode"]">@accessDisplay.Name</a></li>
    }
}

Whiteboard/Views/Shared/_ModulesDisplayPartial.cshtml
@model Whiteboard.Models.ViewModels.Accounts.ModulesViewModel
@using Whiteboard.Models.ViewModels.Accounts

<script src="~/scripts/SecurityLib.js"></script>

<h2 class="common-heading">Your Modules</h2>
<div class="modules-list">
    @if (Model.TakenModules != null && Model.TakenModules.Any()) {
        @foreach (ModuleStartViewModel module in Model.TakenModules) {
            <div class="link-container">
            <a class="common-btn" asp-controller="Module" asp-action="Index" asp-route-code="@module.Code">@module.Code - @module.Name</a>
            </div>
        }
    } else {
        <p class="common-paragraph">You didn't choose any courses</p>
    }
</div>

<br/>

<div class="modules-list">
    <h2 class="common-heading">Available Modules</h2>
    @foreach (ModuleStartViewModel module in Model.AvailableModules) {
        <div class="link-container">
        <a class="module_choice common-btn" data-code="@module.Code">@module.Code - @module.Name</a>
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        $(".module_choice").click(function () {
            var moduleCode = $(this).attr("data-code");

            $.ajax({
                type: "POST",
                url: "@Url.Action("AddModule", "Home")",
                data: AntiForgeryToken({ code: moduleCode }),
                success: function () {
                    location.reload(true);
                }
            });
        });
    });
</script>